[pis]
slot4_ubuntu_server_4gb  ansible_host=192.168.1.175
slot3_kali_pi_8gb        ansible_host=192.168.1.176
slot5_ubuntu_server_2gb  ansible_host=192.168.1.177
slot1_ubuntu_desktop_8gb ansible_host=192.168.1.178
slot2_ubuntu_server_8gb  ansible_host=192.168.1.179

[pis:vars]
ansible_user=super90
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3
